name: tmm-chart
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python=3.10
  - pip
  - git
  - tmux
  - htop
  - jupyterlab
  - numpy
  - scipy
  - scikit-learn
  - matplotlib
  - pillow
  - pyyaml
  - tqdm
  - pip:
      - accelerate>=1.2.1
      - datasets>=3.1.0
      - transformers>=4.47.0
      - peft>=0.13.2
      - sentencepiece
      - protobuf
      - einops
      - opencv-python
      - evaluate
      - bitsandbytes
